version: '3'

services:
  caddy:
        image: docker.io/library/caddy:2-alpine
        restart: unless-stopped
        environment:
            - WEB_DOMAIN=${WEB_DOMAIN}
            - API_DOMAIN=${API_DOMAIN}
        ports:
            - 80:80/tcp
            - 443:443/tcp
            - 443:443/udp
        volumes:
            - ./conf/Caddyfile.${COBALT_MODE}:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
        labels:
            - com.centurylinklabs.watchtower.scope=cobaltkit
  api:
        # todo: change this to wukko/cobalt once #151 is merged
        image: ghcr.io/dumbmoron/cobalt:latest
        restart: unless-stopped
        environment:
            - apiPort=9000
            - apiURL=https://${API_DOMAIN}/
            - apiName=${API_NAME}
            - cors=${CORS}
        depends_on: ["caddy"]
        labels:
            - com.centurylinklabs.watchtower.scope=cobaltkit
  web:
        # todo: change this to wukko/cobalt once #151 is merged
        image: ghcr.io/dumbmoron/cobalt:latest
        restart: unless-stopped
        environment:
            - webPort=9000
            - webURL=https://${WEB_DOMAIN}/
            - apiURL=https://${API_DOMAIN}/
            - cors=${CORS}
        depends_on: ["caddy"]
        labels:
            - com.centurylinklabs.watchtower.scope=cobaltkit
  watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobaltkit --interval 3600
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
  caddy_data:
